// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @honor/player.career
const encoding0_14 = c.array(c.string)

// @honor/player
const encoding0 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
    c.string.preencode(state, m.name)
    state.end++ // max flag is 2 so always one byte

    if (m.memo) c.string.preencode(state, m.memo)
    c.uint.preencode(state, m.spawned)
    c.uint.preencode(state, m.seen)
    c.uint.preencode(state, m.adventures)
    c.string.preencode(state, m.state)
    c.int.preencode(state, m.location)
    c.uint.preencode(state, m.kills)
    c.uint.preencode(state, m.escapes)
    c.uint.preencode(state, m.deaths)
    c.int.preencode(state, m.hp)
    c.uint.preencode(state, m.experience)
    encoding0_14.preencode(state, m.career)
    encoding0_15.preencode(state, m.inventory)
  },
  encode(state, m) {
    const flags = (m.memo ? 1 : 0) | (m.dead ? 2 : 0)

    c.buffer.encode(state, m.key)
    c.string.encode(state, m.name)
    c.uint.encode(state, flags)

    if (m.memo) c.string.encode(state, m.memo)
    c.uint.encode(state, m.spawned)
    c.uint.encode(state, m.seen)
    c.uint.encode(state, m.adventures)
    c.string.encode(state, m.state)
    c.int.encode(state, m.location)
    c.uint.encode(state, m.kills)
    c.uint.encode(state, m.escapes)
    c.uint.encode(state, m.deaths)
    c.int.encode(state, m.hp)
    c.uint.encode(state, m.experience)
    encoding0_14.encode(state, m.career)
    encoding0_15.encode(state, m.inventory)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      name: r1,
      memo: (flags & 1) !== 0 ? c.string.decode(state) : null,
      spawned: c.uint.decode(state),
      seen: c.uint.decode(state),
      adventures: c.uint.decode(state),
      state: c.string.decode(state),
      location: c.int.decode(state),
      kills: c.uint.decode(state),
      escapes: c.uint.decode(state),
      deaths: c.uint.decode(state),
      dead: (flags & 2) !== 0,
      hp: c.int.decode(state),
      experience: c.uint.decode(state),
      career: encoding0_14.decode(state),
      inventory: encoding0_15.decode(state)
    }
  }
}

// @honor/item
const encoding1 = {
  preencode(state, m) {
    c.uint.preencode(state, m.id)
    c.uint.preencode(state, m.qty)
    state.end++ // max flag is 4 so always one byte

    if (m.uid) c.string.preencode(state, m.uid)
    if (m.stats) encoding1_4.preencode(state, m.stats)
  },
  encode(state, m) {
    const flags = (m.uid ? 1 : 0) | (m.equipped ? 2 : 0) | (m.stats ? 4 : 0)

    c.uint.encode(state, m.id)
    c.uint.encode(state, m.qty)
    c.uint.encode(state, flags)

    if (m.uid) c.string.encode(state, m.uid)
    if (m.stats) encoding1_4.encode(state, m.stats)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      qty: r1,
      uid: (flags & 1) !== 0 ? c.string.decode(state) : null,
      equipped: (flags & 2) !== 0,
      stats: (flags & 4) !== 0 ? encoding1_4.decode(state) : null
    }
  }
}

// @honor/item_stats
const encoding2 = {
  preencode(state, m) {
    c.int.preencode(state, m.pwr)
    c.int.preencode(state, m.agl)
    c.int.preencode(state, m.wis)
    c.int.preencode(state, m.atk)
    c.int.preencode(state, m.def)
    c.int.preencode(state, m.mag)
  },
  encode(state, m) {
    c.int.encode(state, m.pwr)
    c.int.encode(state, m.agl)
    c.int.encode(state, m.wis)
    c.int.encode(state, m.atk)
    c.int.encode(state, m.def)
    c.int.encode(state, m.mag)
  },
  decode(state) {
    const r0 = c.int.decode(state)
    const r1 = c.int.decode(state)
    const r2 = c.int.decode(state)
    const r3 = c.int.decode(state)
    const r4 = c.int.decode(state)
    const r5 = c.int.decode(state)

    return {
      pwr: r0,
      agl: r1,
      wis: r2,
      atk: r3,
      def: r4,
      mag: r5
    }
  }
}

// @honor/world_genesis
const encoding3 = {
  preencode(state, m) {
    c.uint.preencode(state, m.version)
    c.string.preencode(state, m.ruleset)
    c.string.preencode(state, m.admission)
    c.buffer.preencode(state, m.topic)
  },
  encode(state, m) {
    c.uint.encode(state, m.version)
    c.string.encode(state, m.ruleset)
    c.string.encode(state, m.admission)
    c.buffer.encode(state, m.topic)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.buffer.decode(state)

    return {
      version: r0,
      ruleset: r1,
      admission: r2,
      topic: r3
    }
  }
}

// @honor/pve-session
const encoding4 = {
  preencode(state, m) {
    c.uint.preencode(state, m.date)
    c.buffer.preencode(state, m.actions)
    c.buffer.preencode(state, m.seed)
    c.buffer.preencode(state, m.author)
    c.uint.preencode(state, m.seq)
  },
  encode(state, m) {
    c.uint.encode(state, m.date)
    c.buffer.encode(state, m.actions)
    c.buffer.encode(state, m.seed)
    c.buffer.encode(state, m.author)
    c.uint.encode(state, m.seq)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.buffer.decode(state)
    const r4 = c.uint.decode(state)

    return {
      date: r0,
      actions: r1,
      seed: r2,
      author: r3,
      seq: r4
    }
  }
}

// @honor/pve-session-v2
const encoding5 = {
  preencode(state, m) {
    c.uint.preencode(state, m.date)
    c.buffer.preencode(state, m.actions)
  },
  encode(state, m) {
    c.uint.encode(state, m.date)
    c.buffer.encode(state, m.actions)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.buffer.decode(state)

    return {
      date: r0,
      actions: r1
    }
  }
}

// @honor/player.inventory, deferred due to recusive use
const encoding0_15 = c.array(c.frame(encoding1))
// @honor/item.stats, deferred due to recusive use
const encoding1_4 = c.frame(encoding2)

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@honor/player':
      return encoding0
    case '@honor/item':
      return encoding1
    case '@honor/item_stats':
      return encoding2
    case '@honor/world_genesis':
      return encoding3
    case '@honor/pve-session':
      return encoding4
    case '@honor/pve-session-v2':
      return encoding5
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
